#!/bin/bash
# The content of this file is a memo for running "initial attach" scenarios
# 
exit(0)

# Have a look at prepare_test script


###############################################
# MEMO ATTACH GUTI SCENARIO
###############################################
# In terminal T1:
cd openair-cn/TEST/SCENARIOS/INITIAL_ATTACH
mv ../../../BUILD/EPC/epc.conf.in ../../../BUILD/EPC/epc.conf.in.save
cp epc.conf.run_attach_guti.in ../../../BUILD/EPC/epc.conf.in

# In terminal T2:
cd openair-cn/SCRIPTS
./build_epc --clean --clean-certificates --local-hss 
./run_epc --set-nw-interfaces --mscgen /tmp

# In terminal T3:
cd openair-cn/SCRIPTS
./build_hss --clean --clean-certificates --local-mme --random false
./run_hss --import-db ../TEST/SCENARIOS/INITIAL_ATTACH/attach_guti.sql

# In terminal T1:
test_epc --run --set-nw-interfaces --test-dir . --enb-config-file enb_local.run_attach_guti.conf --scenario-file attach_guti.xml


###############################################
# MEMO ATTACH UNKNOWN GUTI SCENARIO
###############################################
# In terminal T1:
cd openair-cn/TEST/SCENARIOS/INITIAL_ATTACH
mv ../../../BUILD/EPC/epc.conf.in ../../../BUILD/EPC/epc.conf.in.save
cp epc.conf.run_attach_unknown_guti.in ../../../BUILD/EPC/epc.conf.in

# In terminal T2:
cd openair-cn/SCRIPTS
./build_epc --clean --clean-certificates --local-hss 
./run_epc --set-nw-interfaces --mscgen /tmp

# In terminal T3:
cd openair-cn/SCRIPTS
./build_hss --clean --clean-certificates --local-mme --random false
./run_hss --import-db ../TEST/SCENARIOS/INITIAL_ATTACH/attach_unknown_guti.sql

# In terminal T1:
test_epc --run --set-nw-interfaces --test-dir . --enb-config-file enb_local.run_attach_unknown_guti.conf --scenario-file attach_unknown_guti.xml

