#!/bin/bash

# MEMO
# mv ../../../BUILD/EPC/epc.conf.in ../../../BUILD/EPC/epc.conf.in.save
# cp epc.conf.run_test.in ../../../BUILD/EPC/epc.conf.in
# cd ../../../SCRIPTS
# ./build_epc --clean --local-hss 
# ./build_hss --clean --local-mme --random false
# ./run_epc --set-nw-interfaces --mscgen /tmp
# ./run_hss --import-db ../TEST/SCENARIOS/INITIAL_ATTACH/attach_guti.sql
# cd ../TEST/SCENARIOS/INITIAL_ATTACH
# test_epc --run --test-dir . --enb-config-file enb_local.run_test.conf --scenario-file attach_guti.xml