/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the Apache License, Version 2.0  (the "License"); you may not use this file
 * except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <pthread.h>

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlwriter.h>
#include <libxml/xpath.h>
#include "bstrlib.h"

#include "xml_load.h"
#include "log.h"
#include "msc.h"
#include "assertions.h"
#include "conversions.h"
#include "3gpp_23.003.h"
#include "3gpp_24.008.h"
#include "3gpp_33.401.h"
#include "3gpp_24.007.h"
#include "3gpp_36.401.h"
#include "3gpp_36.331.h"
#include "3gpp_24.301.h"
#include "security_types.h"
#include "securityDef.h"
#include "common_types.h"
#include "mme_api.h"
#include "emm_data.h"
#include "emm_msg.h"
#include "esm_msg.h"
#include "intertask_interface.h"
#include "timer.h"
#include "dynamic_memory_check.h"
#include "common_defs.h"
#include "mme_scenario_player.h"
#include "xml_msg_tags.h"
#include "xml_msg_load_itti.h"
#include "xml_msg_dump.h"
#include "xml_msg_dump_itti.h"
#include "itti_free_defined_msg.h"
#include "itti_comp.h"
#include "sp_xml_compare.h"

extern scenario_player_t g_msp_scenarios;

// TODO code bellow can be generated by a macro

//------------------------------------------------------------------------------
void mme_scenario_player_handle_nas_downlink_data_req (instance_t instance, const MessageDef * const received_message)
{
  // get message specified in scenario
  scenario_t *scenario = g_msp_scenarios.current_scenario;
  if (!scenario) {
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No scenario started, NAS_DOWNLINK_DATA_REQ discarded\n");
    return;
  }

  OAILOG_NOTICE(LOG_MME_SCENARIO_PLAYER, "Received NAS_DOWNLINK_DATA_REQ message\n");

  pthread_mutex_lock(&scenario->lock);
  scenario_player_item_t *item = scenario->last_played_item;
  if (item) item = item->next_item;

  if (!item) {
    pthread_mutex_unlock(&scenario->lock);
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No Pending RX message in scenario, NAS_DOWNLINK_DATA_REQ discarded\n");
    return;
  }

  if ((SCENARIO_PLAYER_ITEM_ITTI_MSG == item->item_type) && !(item->u.msg.is_tx) && !(item->is_played)) {
    if (NAS_DOWNLINK_DATA_REQ == ITTI_MSG_ID (item->u.msg.itti_msg)) {
      // OK messages seems to match
      if (item->u.msg.timer_id) {
        timer_remove(item->u.msg.timer_id);
      }
      msp_get_elapsed_time_since_scenario_start(scenario, &item->u.msg.time_stamp);

      OAILOG_TRACE(LOG_MME_SCENARIO_PLAYER, "Found matching NAS_DOWNLINK_DATA_REQ message UID %d\n", item->uid);

      const itti_nas_dl_data_req_t * const nas_dl_data_req = &NAS_DL_DATA_REQ (received_message);

      //-------------------------------
      // Dump received message in XML
      //-------------------------------
      xmlTextWriterPtr xml_text_writer = NULL;
      char             filename[NAME_MAX+9];
      if (snprintf(filename, sizeof(filename), "/tmp/mme_msg_%06lu_%s.xml", xml_msg_dump_get_seq_uid(), ITTI_NAS_DOWNLINK_DATA_REQ_XML_STR) <= 0) {
        scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        pthread_mutex_unlock(&scenario->lock);
        OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "xmlTextWriterStartDocument\n");
        return;
      }
      /* Create a new XmlWriter for uri, with no compression. */
      xml_text_writer = xmlNewTextWriterFilename(filename, 0);
      if (xml_text_writer == NULL) {
        scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "Error creating the xml writer\n");
      } else {
        xml_msg_dump_itti_nas_downlink_data_req(nas_dl_data_req, received_message->ittiMsgHeader.originTaskId, TASK_MME_SCENARIO_PLAYER, xml_text_writer);
        int rc = xmlTextWriterEndDocument(xml_text_writer);
        if (0 > rc) {
          OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "Error ending Document\n");
        }
        xmlFreeTextWriter(xml_text_writer);

        // OLE.... pretty xml
        char cmd[400];
        snprintf(cmd, 400, "tmpfile=`mktemp`;xmllint --format %s > $tmpfile; cp $tmpfile %s;rm  $tmpfile", filename, filename);
        system(cmd);

        //-------------------------------
        // Compare (in XML) received message with scenario message
        //-------------------------------
        xmlDoc *doc = xmlReadFile(filename, NULL, 0);
        if (sp_compare_xml_docs(scenario, doc, item->u.msg.xml_doc)) {
          scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        } else {
          if (SCENARIO_STATUS_PAUSED == scenario->status) {
            scenario_set_status(scenario, SCENARIO_STATUS_PLAYING);
          }
        }
        xmlFreeDoc(doc);
      }
      item->is_played = true;
    } else {
      scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
      OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "Pending RX message in scenario is not NAS_DOWNLINK_DATA_REQ, scenario failed\n");
    }
    scenario->last_played_item = item;
    pthread_mutex_unlock(&scenario->lock);
    msp_scenario_tick(scenario);
    return;
  } else {
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No Pending RX message in scenario, NAS_DOWNLINK_DATA_REQ discarded\n");
  }
  pthread_mutex_unlock(&scenario->lock);
}
//------------------------------------------------------------------------------
void mme_scenario_player_handle_mme_app_connection_establishment_cnf (instance_t instance, const MessageDef * const received_message)
{
  // get message specified in scenario
  scenario_t *scenario = g_msp_scenarios.current_scenario;
  if (!scenario) {
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No scenario started, MME_APP_CONNECTION_ESTABLISHMENT_CNF discarded\n");
    return;
  }

  pthread_mutex_lock(&scenario->lock);
  scenario_player_item_t *item = scenario->last_played_item;
  if (item) item = item->next_item;
  else {
    pthread_mutex_unlock(&scenario->lock);
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No Pending RX message in scenario, MME_APP_CONNECTION_ESTABLISHMENT_CNF discarded\n");
    return;
  }

  if ((SCENARIO_PLAYER_ITEM_ITTI_MSG == item->item_type) && !(item->u.msg.is_tx) && !(item->is_played)) {
    if (MME_APP_CONNECTION_ESTABLISHMENT_CNF == ITTI_MSG_ID (item->u.msg.itti_msg)) {
      // OK messages seems to match
      msp_get_elapsed_time_since_scenario_start(scenario, &item->u.msg.time_stamp);
      const itti_mme_app_connection_establishment_cnf_t * const mme_app_connection_establishment_cnf = &MME_APP_CONNECTION_ESTABLISHMENT_CNF (received_message);

      //-------------------------------
      // Dump received message in XML
      //-------------------------------
      xmlTextWriterPtr xml_text_writer = NULL;
      char             filename[NAME_MAX+9];
      if (snprintf(filename, sizeof(filename), "/tmp/mme_msg_%06lu_%s.xml", xml_msg_dump_get_seq_uid(), ITTI_MME_APP_CONNECTION_ESTABLISHMENT_CNF_XML_STR) <= 0) {
        scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        pthread_mutex_unlock(&scenario->lock);
        OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "xmlTextWriterStartDocument\n");
        return;
      }
      /* Create a new XmlWriter for uri, with no compression. */
      xml_text_writer = xmlNewTextWriterFilename(filename, 0);
      if (xml_text_writer == NULL) {
        scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "Error creating the xml writer\n");
      } else {
        xml_msg_dump_itti_mme_app_connection_establishment_cnf(mme_app_connection_establishment_cnf, received_message->ittiMsgHeader.originTaskId, TASK_MME_SCENARIO_PLAYER, xml_text_writer);

        //-------------------------------
        // Compare (in XML) received message with scenario message
        //-------------------------------
        xmlDoc *doc = xmlReadFile(filename, NULL, 0);
        if (sp_compare_xml_docs(scenario, doc, item->u.msg.xml_doc)) {
          scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
        }
        xmlFreeDoc(doc);
      }

      item->is_played = true;
    } else {
      scenario_set_status(scenario, SCENARIO_STATUS_PLAY_FAILED);
      OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "Pending RX message in scenario is not MME_APP_CONNECTION_ESTABLISHMENT_CNF, scenario failed\n");
    }
  } else {
    OAILOG_ERROR(LOG_MME_SCENARIO_PLAYER, "No Pending RX message in scenario, MME_APP_CONNECTION_ESTABLISHMENT_CNF discarded\n");
  }
  pthread_mutex_unlock(&scenario->lock);

}

