#!/bin/bash
# The content of this file is a memo for preparing "TAU" scenarios
# 
exit(0)

# generate XML scenario file
cd openair-cn/TEST/SCENARIOS/TAU
test_epc --build-test --test-dir . --old-enb-config-file tau_req_same_tai_unknown_ue.enb.band7.tm1.usrpb210.epc.remote.conf --pcap-file tau_req_same_tai_unknown_ue.pcapng


