#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the terms found in the LICENSE file in the root of this source tree.
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface HSS service
#   Valid for Ubuntu-18.04 (bionic)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-hss-builder

ARG EURECOM_PROXY

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git && \
    rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN /bin/bash -c "if [[ -v EURECOM_PROXY ]]; then git config --global http.proxy $EURECOM_PROXY; fi"
RUN git config --global https.postBuffer 123289600
RUN git config --global http.sslverify false

# Copy the workspace as is
WORKDIR /openair-hss
COPY . .

# wait for it
workdir /
RUN git clone https://github.com/vishnubob/wait-for-it.git

# Installing and Building HSS
WORKDIR /openair-hss/scripts
RUN ./build_hss_rel14 --check-installed-software --force
RUN ./build_hss_rel14 --clean --build-type Release

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-hss
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      tzdata \
      psmisc \
      openssl \
      net-tools \
      tshark \
      libsctp1 \
      libuv1 \
      libconfig9 \
      libidn11 \
      python \
      python3 \
      python-cassandra \
      python3-cassandra && \
    rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-hss/bin
COPY --from=oai-hss-builder /openair-hss/build/hss_rel14/bin/hss oai_hss
COPY --from=oai-hss-builder /openair-hss/scripts/entrypoint.sh .

COPY --from=oai-hss-builder /usr/local/lib/libfd* /usr/local/lib/
COPY --from=oai-hss-builder /usr/local/lib/freeDiameter/* /usr/local/lib/freeDiameter/
COPY --from=oai-hss-builder /usr/local/lib/x86_64-linux-gnu/libcassandra* /usr/local/lib/

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-hss/etc
COPY --from=oai-hss-builder /openair-hss/etc/hss_rel14.conf .
COPY --from=oai-hss-builder /openair-hss/etc/hss_rel14.json .
RUN sed -i -e 's#freeDiameter##' hss_rel14.json
COPY --from=oai-hss-builder /openair-hss/etc/acl.conf .
COPY --from=oai-hss-builder /openair-hss/etc/oss.json .
COPY --from=oai-hss-builder /openair-hss/etc/hss_rel14_fd.conf .
RUN sed -i -e "s#@PREFIX@/freeDiameter#@PREFIX@#g" hss_rel14_fd.conf

# Copy the certificate generation script
WORKDIR /openair-hss/scripts
COPY --from=oai-hss-builder /openair-hss/src/hss_rel14/bin/make_certs.sh .
COPY --from=oai-hss-builder /openair-hss/scripts/data_provisioning_users .
COPY --from=oai-hss-builder /openair-hss/scripts/data_provisioning_mme .
COPY --from=oai-hss-builder /wait-for-it/wait-for-it.sh .
RUN sed -i -e "s@/freeDiameter@@" make_certs.sh

WORKDIR /openair-hss
RUN openssl rand -out /root/.rnd 128

# expose ports configured in hss_fd.conf
EXPOSE 9042/tcp 5868/tcp 9080/tcp 9081/tcp

CMD ["/openair-hss/bin/oai_hss", "-j", "/openair-hss/etc/hss_rel14.json", "--reloadkey", "true"]
ENTRYPOINT ["/openair-hss/bin/entrypoint.sh"]
