#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the terms found in the LICENSE file in the root of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file build_hss_rel14
# brief
# author Tien-Thinh NGUYEN
# company Eurecom
# email: tien-thinh.nguyen@eurecom.fr
#
################################
# include helper functions
################################
HSS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $HSS_SCRIPT_PATH/../build/tools/build_helper.hss_rel14


function help()
{
  echo_error " "
  echo_error "Usage: build_hss_rel14 [OPTION]..."
  echo_error "Build the experimental HSS executable. (oai_hss)"
  echo_error " "
  echo_error "Options:"
  echo_error "Mandatory arguments to long options are mandatory for short options too."
  echo_error "  -b, --build-type                          Build type as defined in cmake, allowed values are: Debug Release RelWithDebInfo MinSizeRel"
  echo_error "  -c, --clean                               Clean the build generated files: config, object, executable files (build from scratch)"
  echo_error "  -d, --debug                               Compile with debug informations."
  echo_error "  -f, --force                               No interactive script for installation of software packages."
  echo_error "  -h, --help                                Print this help."
  echo_error "  -i, --check-installed-software            Check installed software packages necessary to build and run HSS (support $SUPPORTED_DISTRO)."
  echo_error "                                            If filled, then OPc key in table users for all subscribers (IMSI) will be computed/updated."
  echo_error "  -v, --verbose                             Build process verbose."
}

function main()
{
  local -i clean=0
  local -i verbose=0
  local -i var_check_install_oai_software=0
  local -i force=0
  local    cmake_args=" "
  local    opt_args=''
  local    function_args="Debug"
  local    make_args="-j`nproc`"
  local    realm=""

  until [ -z "$1" ]; do
    case "$1" in
      -b | --build-type)
        list_include_item "Debug Release RelWithDebInfo MinSizeRel" $2
        [[ $? -ne 0 ]] && echo_error "Build type $2 not recognized" && return $?
        cmake_args="$cmake_args -DCMAKE_BUILD_TYPE=$2"
        function_args=$2
        case "$2" in
          Release)
            opt_args='COPT_FLAGS="-O3"'
            ;;
          Debug)
            opt_args='COPT_FLAGS="-g"'
            ;;
          RelWithDebInfo)
            opt_args='COPT_FLAGS="-Og"'
            ;;
          MinSizeRel)
            opt_args='COPT_FLAGS="-Os"'
            ;;
        esac
        shift 2;
        ;;
      -c | --clean)
        clean=1
        echo "Clean the build generated files (build from scratch)"
        shift;
        ;;
      -d | --debug)
        make_args="$make_args -DDEBUG=1"
        echo "Compile with debug informations"
        shift;
        ;;
      -f | --force)
        force=1
        echo "Force set (no interactive)"
        shift;
        ;;
      -h | --help)
        help
        return 0
        ;;
      -i | --check-installed-software)
        echo "Check installed software packages necessary to build and run HSS (support $SUPPORTED_DISTRO):"
        set_openair_env
        var_check_install_oai_software=1
        shift;
        ;;
      -v | --verbose)
        echo "Make build process verbose"
        cmake_args="$cmake_args -DCMAKE_VERBOSE_MAKEFILE=ON"
        make_args="VERBOSE=1 $make_args"
        verbose=1
        shift;
        ;;
      *)   
        echo "Unknown option $1"
        help
        return 1
        ;;
    esac
  done

  if [ $clean -ne 0 ]; then
    if [[ $verbose -eq 1 ]]; then
      echo "Cleaning HSS"
    fi
    rm -Rf $HSS_SCRIPT_PATH/../build/hss_rel14/build 2>&1
    mkdir -m 777 -p -v $HSS_SCRIPT_PATH/../build/hss_rel14/build
  fi
  if [ ! -d $HSS_SCRIPT_PATH/../build/hss_rel14/build ]; then
    mkdir -m 777 -p -v $HSS_SCRIPT_PATH/../build/hss_rel14/build
  fi

  if [ $var_check_install_oai_software -gt 0 ];then
    update_package_db
    [[ $? -ne 0 ]] && return $?
    
    check_install_hss_software  $force
    if [ $? -ne 0 ]; then
        echo_error "Error: HSS software installation failed"
        return 1
    else
        echo_success "HSS software installation successful"
        echo "HSS not compiled, to compile it, re-run build_hss without -i option"
        return 0
    fi
  fi

  set_openair_env
  if [[ $verbose -eq 1 ]]; then
    cecho "OPENAIRCN_DIR    = $OPENAIRCN_DIR" $green
  fi
  
  if [[ z$OPENAIRCN_DIR = z ]]; then
    echo_error "OPENAIRCN_DIR env variable not set, exiting"
    return 1
  fi


  local dlog=$OPENAIRCN_DIR/build/log

  mkdir -m 777 -p $dlog


  cmake_args="$cmake_args -DOPENAIRCN_DIR=$OPENAIRCN_DIR"

  build_util $function_args
  ret=$?;[[ $ret -ne 0 ]] && return $ret
  build_hsssec $function_args
  ret=$?;[[ $ret -ne 0 ]] && return $ret
  cd $OPENAIRCN_DIR/build/hss_rel14
  make $make_args $opt_args
  ret=$?;[[ $ret -ne 0 ]] && return $ret
  chmod -f 777 *

  $SUDO killall -q oai_hss
  $SUDO cp -upv $OPENAIRCN_DIR/build/hss_rel14/bin/hss /usr/local/bin/oai_hss && echo_success "oai_hss installed"
  return 0
}


main "$@"


