#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file build_epc
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
#
################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/../BUILD/TOOLS/build_helper

function help()
{
  echo_error " "
  echo_error "Usage: build_epc [OPTION]..."
  echo_error "Build the EPC executable (MME+SP-GW)."
  echo_error " "
  echo_error "Options:"
  echo_error "Mandatory arguments to long options are mandatory for short options too."
  echo_error "  -c, --clean                               Clean the build generated files: config, object, executable files (build from scratch)"
  echo_error "  -C, --conf-files-only                     Generate only EPC configuration files (no build)"
  echo_error "  -D, --daemon                              Build EPC as a daemon."
  echo_error "  -f, --force                               No interactive script for installation of software packages."
  echo_error "  -h, --help                                Print this help."
  echo_error "  -i, --check-installed-software            Check installed software packages necessary to build and run EPC (support Ubuntu 14.04)."
  echo_error "  -j, --install-gtpu-kernel-module          Install or reinstall specifically the GTPV1-U kernel module (done with -i also) (support Ubuntu 14.04)."
  echo_error "  -t, --install-xtables                     Install or reinstall only xtables without the linux headers."
  echo_error "  -v, --verbose                             Build process verbose."
  echo_error "  -V, --verbose-make                        Make process verbose."
}

NAME=mme_gwd
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid


function main()
{
  local -i clean=0
  local -i clean_certificates=0
  local -i conf_files_only=0
  local -i daemon=0
  local -i force=0
  local -i verbose=0
  local -i s6a_server=0
  local -i install_gtpu_kernel_module=0
  local -i install_xtables=0
  local -i var_check_install_oai_software=0
  local    make_args="-j $NUM_CPU"
  
  export    cmake_args=" "


  until [ -z "$1" ]
    do
    case "$1" in
      -c | --clean)
        clean=1
        echo "Clean the build generated files (build from scratch)"
        shift;
        ;;
      -C | --conf-files-only)
        conf_files_only=1
        echo "Generate only conf files (no build)"
        shift;
        ;;
      -D | --daemon)
        daemon=1
        cmake_args="$cmake_args -DDAEMONIZE=1"
        echo "Build EPC as a daemon"
        shift;
        ;;
      -f | --force)
        force=1
        echo "Force set (no interactive)"
        shift;
        ;;
      -h | --help)
        help
        shift;
        exit 0
        ;;
      -i | --check-installed-software)
        echo "Check installed software packages necessary to build and run EPC (support Ubuntu 14.04):"
        set_openair_env
        var_check_install_oai_software=1
        shift;
        ;;
      -j | --install-gtpu-kernel-module)
        set_openair_env
        install_gtpu_kernel_module=1
        shift;
        ;;
      -t | --install-xtables)
        install_xtables=1
        shift;
        ;;
      -v | --verbose)
        echo "Build process verbose"
        verbose=1
        shift;
        ;;
      -V | --verbose-make)
        echo "Make build process verbose"
        cmake_args="$cmake_args -DCMAKE_VERBOSE_MAKEFILE=ON"
        make_args="VERBOSE=1 $make_args"
        verbose=1
        shift;
        ;;
      -x | --clean-certificates)
        clean_certificates=1
        echo "Clean the MME certificates"
        shift;
        ;;
      *)   
        echo "Unknown option $1"
        help
        exit 1
        ;;
    esac
  done
  
  if [ $install_gtpu_kernel_module -gt 0 ];then
    check_kernel_release_and_install_xtables_addons_oai 3.19.0-28-generic $force
    exit 0
  fi 
  
  if [ $install_xtables -gt 0 ]; then 
    install_xtables_addons_oai $force
    exit 0   
  fi

  if [ $var_check_install_oai_software -gt 0 ];then
    update_package_db
    check_install_mme_gw_software  $force 
    exit 0
  fi
  
  set_openair_env 
  $SUDO cp -uv  $OPENAIRCN_DIR/SCRIPTS/mme_test_s1_pcap2pdml /usr/local/bin
  $SUDO chmod 755 /usr/local/bin/mme_test_s1_pcap2pdml
   
  $SUDO cp -uv  $OPENAIRCN_DIR/SCRIPTS/test_epc              /usr/local/bin
  $SUDO chmod 755 /usr/local/bin/test_epc 
  
  $SUDO mkdir -p -m 755 /usr/share/oai/xsl
  $SUDO cp -upv  $OPENAIRCN_DIR/SRC/TEST/SCENARIOS/play_scenario.xsl    /usr/share/oai/xsl
  $SUDO cp -upv  $OPENAIRCN_DIR/SRC/TEST/SCENARIOS/generic_scenario.xsl /usr/share/oai/xsl
  
  

  if [[ $verbose -eq 1 ]]; then
    cecho "OPENAIRCN_DIR    = $OPENAIRCN_DIR" $green
  fi
  
  
  
  
  local dlog=$OPENAIRCN_DIR/BUILD/LOG
  
  mkdir -m 777 -p $dlog
  
  ##############################################################################
  # Clean
  ##############################################################################
  cd $OPENAIRCN_DIR/BUILD/EPC
  if [ $clean -ne 0 ]; then
    if [[ $verbose -eq 1 ]]; then
      echo "Cleaning EPC: obj files, mme_gw executable"
    fi
    rm -Rf $OPENAIRCN_DIR/BUILD/EPC/BUILD  2>&1
    mkdir -m 777 -p -v BUILD
  fi
  
  ##############################################################################
  # Compile EPC
  ##############################################################################
  cd $OPENAIRCN_DIR/BUILD/EPC
  if [ ! -d ./BUILD ]; then
    mkdir -m 777 -p -v BUILD
  fi
  cmake_file=./CMakeLists.txt
  cp $OPENAIRCN_DIR/BUILD/EPC/CMakeLists.template $cmake_file
  echo 'include(${CMAKE_CURRENT_SOURCE_DIR}/../CMakeLists.txt)' >> $cmake_file
  
  cd ./BUILD
  cmake  $cmake_args .. > /dev/null 
  
  if [ $conf_files_only -eq 0 ]; then
    compilations EPC mme_gw mme_gw $verbose
    if [ $daemon -ne 0 ]; then
      do_stop_daemon
      $SUDO cp -upv $OPENAIRCN_DIR/BUILD/EPC/BUILD/mme_gw /usr/sbin/mme_gwd && echo_success "mme_gwd installed"
    else
      $SUDO killall -q mme_gw
      $SUDO cp -upv $OPENAIRCN_DIR/BUILD/EPC/BUILD/mme_gw /usr/local/bin/ && echo_success "mme_gw installed"
    fi
    compilations EPC auth_request auth_request 
    $SUDO cp -upv $OPENAIRCN_DIR/BUILD/EPC/BUILD/auth_request /usr/local/bin/ && echo_success "auth_request installed"
  fi
}


main "$@"


