#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
# file prepare_test_scenarios
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
# 

export THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))

# find in all subdirectories a valid test to play
# that mean a directory must contain a valid set of files

list_dir_name="`find $THIS_SCRIPT_PATH/../TEST/SCENARIOS -type d | sort | uniq`"

for dirname_name in $list_dir_name
do
  cd $dirname_name > /dev/null 2>&1
  $THIS_SCRIPT_PATH/prepare_test_scenario
  cd - > /dev/null 2>&1
done


