#!/bin/bash

# generate XML scenario file we assume we are in cd openair-cn/TEST/SCENARIOS/INITIAL_ATTACH
test_epc --build-test --test-dir . --old-enb-config-file attach_guti.enb.conf --pcap-file attach_guti.pcapng
test_epc --build-test --test-dir . --old-enb-config-file attach_unknown_guti.enb.conf --pcap-file attach_unknown_guti.pcapng

