#!/bin/bash
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under 
# the Apache License, Version 2.0  (the "License"); you may not use this file
# except in compliance with the License.  
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################

# file run_hss
# brief run script for HSS (!EXPERIMENTAL!).
# author  Lionel GAUTHIER
# company Eurecom
# email:  lionel.gauthier@eurecom.fr 


################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/../BUILD/TOOLS/build_helper


function help()
{
  echo_error " "
  echo_error "Usage: run_hss [OPTION]..."
  echo_error "Run the HSS executable (experimental)."
  echo_error " "
  echo_error "Options:"
  echo_error "Mandatory arguments to long options are mandatory for short options too."
  echo_error "  -g, --gdb                  Run with GDB."
  echo_error "  -h, --help                 Print this help."
}



function main() 
{
  local -i run_gdb=0
  local exe_arguments=" -c /usr/local/etc/oai/hss.conf"

  until [ -z "$1" ]
    do
    case "$1" in
      -g | --gdb)
        run_gdb=1
        echo "setting GDB flag to: $GDB"
        shift;
        ;;
      -h | --help)
        help
        exit 0
        ;;
      *)   
        echo "Unknown option $1"
        help
        exit 0
        ;;
    esac
  done

  set_openair_env 
  cecho "OPENAIRCN_DIR   = $OPENAIRCN_DIR" $green


  if [ $run_gdb -eq 0 ]; then 
    exec oai_hss  `echo $exe_arguments` 2>&1 
  else
    touch      ~/.gdb_hss
    chmod 777  ~/.gdb_hss
    echo "file oai_hss" > ~/.gdb_hss
    echo "set args $exe_arguments   " >> ~/.gdb_hss
    echo "run"                        >> ~/.gdb_hss
    cat ~/.gdb_hss
    gdb -n -x ~/.gdb_hss 2>&1
  fi
}


main "$@"
