/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-CommonDataTypes"
 * 	found in "S1AP-CommonDataTypes.asn"
 */

#ifndef _S1ap_ProtocolExtensionID_H_
#define _S1ap_ProtocolExtensionID_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S1ap-ProtocolExtensionID */
typedef long S1ap_ProtocolExtensionID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1ap_ProtocolExtensionID;
asn_struct_free_f S1ap_ProtocolExtensionID_free;
asn_struct_print_f S1ap_ProtocolExtensionID_print;
asn_constr_check_f S1ap_ProtocolExtensionID_constraint;
ber_type_decoder_f S1ap_ProtocolExtensionID_decode_ber;
der_type_encoder_f S1ap_ProtocolExtensionID_encode_der;
xer_type_decoder_f S1ap_ProtocolExtensionID_decode_xer;
xer_type_encoder_f S1ap_ProtocolExtensionID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif /* _S1ap_ProtocolExtensionID_H_ */
#include <asn_internal.h>
