/*
 * Copyright (c) 2015, EURECOM (www.eurecom.fr)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <pthread.h>

#include <libxml/xmlwriter.h>
#include <libxml/xpath.h>
#include "bstrlib.h"

#include "dynamic_memory_check.h"
#include "hashtable.h"
#include "obj_hashtable.h"
#include "log.h"
#include "assertions.h"
#include "3gpp_23.003.h"
#include "3gpp_24.008.h"
#include "3gpp_33.401.h"
#include "3gpp_24.007.h"
#include "3gpp_36.401.h"
#include "3gpp_36.331.h"
#include "3gpp_33.401.h"
#include "security_types.h"
#include "common_types.h"
#include "common_defs.h"
#include "mme_scenario_player.h"
#include "3gpp_36.401_xml.h"

#include "xml2_wrapper.h"


NUM_FROM_XML_GENERATE( enb_ue_s1ap_id , ENB_UE_S1AP_ID );
NUM_FROM_XML_GENERATE( mme_ue_s1ap_id , MME_UE_S1AP_ID );

//------------------------------------------------------------------------------
// could be generated by a macro
//bool enb_ue_s1ap_id_from_xml (
//    scenario_t            * const scenario,
//    scenario_player_msg_t * const msg,
//    enb_ue_s1ap_id_t      * const enb_ue_s1ap_id)
//{
//  bstring xpath_expr = bformat("./%s",ENB_UE_S1AP_ID_IE_XML_STR);
//  bstring xml_var = NULL;
//  bool res = msp_xml_msg_load_leaf_tag(msg->xml_doc, msg->xpath_ctx, xpath_expr, ENB_UE_S1AP_ID_XML_SCAN_FMT, (void*)enb_ue_s1ap_id, &xml_var);
//  if (!res && xml_var) {
//    if ('$' == xml_var->data[0]) {
//      if (BSTR_OK == bdelete(xml_var, 0, 1)) { // delete first char
//        void           *uid = NULL;
//        // is var declared ?
//        hashtable_rc_t rc = obj_hashtable_ts_get (scenario->var_items, bdata(xml_var), blength(xml_var), (void**)&uid);
//        if (HASH_TABLE_OK == rc) {
//          scenario_player_item_t * var_item = NULL;
//          rc = hashtable_ts_get (scenario->scenario_items, (const hash_key_t)(uintptr_t)uid, (void **)&var_item);
//          if ((HASH_TABLE_OK == rc) && (SCENARIO_PLAYER_ITEM_VAR == var_item->item_type)){
//            *enb_ue_s1ap_id = (enb_ue_s1ap_id_t)var_item->u.var.u.value_u64;
//            res = true;
//            msp_msg_add_var_listener(scenario, PARENT_STRUCT(msg, struct scenario_player_item_s, u.msg), var_item);
//            OAILOG_TRACE (LOG_MME_SCENARIO_PLAYER, "Set %s=" ENB_UE_S1AP_ID_XML_FMT " from var uid=0x%lx\n",
//                ENB_UE_S1AP_ID_IE_XML_STR, *enb_ue_s1ap_id, (uintptr_t)uid);
//          } else {
//            AssertFatal (0, "Could not find %s var uid, should have been declared in scenario\n", ENB_UE_S1AP_ID_IE_XML_STR);
//          }
//        } else {
//          AssertFatal (0, "Could not find %s var, should have been declared in scenario\n", ENB_UE_S1AP_ID_IE_XML_STR);
//        }
//      }
//    } else if ('#' == xml_var->data[0]) {
//      if (BSTR_OK == bdelete(xml_var, 0, 1)) { // delete first char
//        void           *uid = NULL;
//        // is var declared ?
//        hashtable_rc_t rc = obj_hashtable_ts_get (scenario->var_items, bdata(xml_var), blength(xml_var), (void**)&uid);
//        if (HASH_TABLE_OK == rc) {
//          scenario_player_item_t * var_item = NULL;
//          rc = hashtable_ts_get (scenario->scenario_items, (const hash_key_t)(uintptr_t)uid, (void **)&var_item);
//          if ((HASH_TABLE_OK == rc) && (SCENARIO_PLAYER_ITEM_VAR == var_item->item_type)){
//            res = true;
//            msp_msg_add_var_to_be_loaded(scenario, msg, var_item);
//            OAILOG_TRACE (LOG_MME_SCENARIO_PLAYER, "Set %s to be loaded\n", ENB_UE_S1AP_ID_IE_XML_STR);
//          } else {
//            AssertFatal (0, "Could not find %s var uid, should have been declared in scenario\n", ENB_UE_S1AP_ID_IE_XML_STR);
//          }
//        } else {
//          AssertFatal (0, "Could not find %s var, should have been declared in scenario\n", ENB_UE_S1AP_ID_IE_XML_STR);
//        }
//      }
//    }
//    bdestroy(xml_var);
//  }
//  bdestroy(xpath_expr);
//  return res;
//}
//------------------------------------------------------------------------------
void enb_ue_s1ap_id_to_xml (const enb_ue_s1ap_id_t * const enb_ue_s1ap_id, xmlTextWriterPtr writer)
{
  XML_WRITE_FORMAT_ELEMENT(writer, ENB_UE_S1AP_ID_IE_XML_STR, ENB_UE_S1AP_ID_XML_FMT, *enb_ue_s1ap_id);
}
//------------------------------------------------------------------------------
// could be generated by a macro
//bool mme_ue_s1ap_id_from_xml (
//    scenario_t            * const scenario,
//    scenario_player_msg_t * const msg,
//    mme_ue_s1ap_id_t      * const mme_ue_s1ap_id)
//{
//  bstring xpath_expr = bformat("./%s",MME_UE_S1AP_ID_IE_XML_STR);
//  bstring xml_var = NULL;
//  bool res = msp_xml_msg_load_leaf_tag(msg->xml_doc, msg->xpath_ctx, xpath_expr, MME_UE_S1AP_ID_XML_SCAN_FMT, (void*)mme_ue_s1ap_id, &xml_var);
//  if (!res && xml_var) {
//    if ('$' == xml_var->data[0]) {
//      if (BSTR_OK == bdelete(xml_var, 0, 1)) { // delete first char
//        void           *uid = NULL;
//        // is var declared ?
//        hashtable_rc_t rc = obj_hashtable_ts_get (scenario->var_items, bdata(xml_var), blength(xml_var), (void**)&uid);
//        if (HASH_TABLE_OK == rc) {
//          scenario_player_item_t * var_item = NULL;
//          rc = hashtable_ts_get (scenario->scenario_items, (const hash_key_t)(uintptr_t)uid, (void **)&var_item);
//          if ((HASH_TABLE_OK == rc) && (SCENARIO_PLAYER_ITEM_VAR == var_item->item_type)){
//            *mme_ue_s1ap_id = (mme_ue_s1ap_id_t)var_item->u.var.u.value_u64;
//            res = true;
//            msp_msg_add_var_listener(scenario, PARENT_STRUCT(msg, struct scenario_player_item_s, u.msg), var_item);
//            OAILOG_TRACE (LOG_MME_SCENARIO_PLAYER, "Set %s="MME_UE_S1AP_ID_XML_FMT" from var uid=0x%lx\n", MME_UE_S1AP_ID_IE_XML_STR, *mme_ue_s1ap_id, (uintptr_t)uid);
//          } else {
//            AssertFatal (0, "Could not find %s var uid, should have been declared in scenario\n", MME_UE_S1AP_ID_IE_XML_STR);
//          }
//        } else {
//          AssertFatal (0, "Could not find %s var, should have been declared in scenario\n", MME_UE_S1AP_ID_IE_XML_STR);
//        }
//      }
//    } else if ('#' == xml_var->data[0]) {
//      if (BSTR_OK == bdelete(xml_var, 0, 1)) { // delete first char
//        void           *uid = NULL;
//        // is var declared ?
//        hashtable_rc_t rc = obj_hashtable_ts_get (scenario->var_items, bdata(xml_var), blength(xml_var), (void**)&uid);
//        if (HASH_TABLE_OK == rc) {
//          scenario_player_item_t * var_item = NULL;
//          rc = hashtable_ts_get (scenario->scenario_items, (const hash_key_t)(uintptr_t)uid, (void **)&var_item);
//          if ((HASH_TABLE_OK == rc) && (SCENARIO_PLAYER_ITEM_VAR == var_item->item_type)){
//            res = true;
//            msp_msg_add_var_to_be_loaded(scenario, msg, var_item);
//            OAILOG_TRACE (LOG_MME_SCENARIO_PLAYER, "Set %s to be loaded\n", MME_UE_S1AP_ID_IE_XML_STR);
//          } else {
//            AssertFatal (0, "Could not find %s var uid, should have been declared in scenario\n", MME_UE_S1AP_ID_IE_XML_STR);
//          }
//        } else {
//          AssertFatal (0, "Could not find %s var, should have been declared in scenario\n", MME_UE_S1AP_ID_IE_XML_STR);
//        }
//      }
//    }
//    bdestroy(xml_var);
//  }
//  bdestroy(xpath_expr);
//  return res;
//}
//------------------------------------------------------------------------------
void mme_ue_s1ap_id_to_xml (const mme_ue_s1ap_id_t * const mme_ue_s1ap_id, xmlTextWriterPtr writer)
{
  XML_WRITE_FORMAT_ELEMENT(writer, MME_UE_S1AP_ID_IE_XML_STR, MME_UE_S1AP_ID_XML_FMT, *mme_ue_s1ap_id);
}

